pool:
  vmImage: 'macos-13'

trigger:
  - '*'

steps:

  - task: InstallAppleCertificate@2
    inputs:
      certSecureFile: 'Testing.mobileprovision'

  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: 7.0.x

  - pwsh: dotnet workload install maui
  - pwsh: |
      dotnet workload list
      dotnet workload --info
      dotnet --info
      dotnet workload update --print-rollback

  - pwsh: zsh build.sh

  - publish: output
    artifact: windows
    condition: always()
