pool:
  vmImage: 'windows-latest'

stages:
  - stage: A
    jobs:
      - job: A1
        steps:
          - checkout: none
          - bash: echo "##vso[task.setvariable variable=name;isOutput=true]name here"
            name: printvar
      - job: A2
        steps:
          - checkout: none
          - bash: echo "##vso[task.setvariable variable=name;isOutput=true]name here"
      - job: A3
        steps:
          - checkout: none

  - stage: B
    dependsOn: A
    variables:
      jobsInStageA: $[ convertToJson(stageDependencies.A) ]
    jobs:
      - job: B1
        steps:
          - checkout: none
          - pwsh: |
              $test=@'
              $(jobsInStageA)
              '@
              echo $test
