pool:
  vmImage: 'windows-latest'

stages:
  - stage: A
    jobs:
      - job: A1
        steps:
          - checkout: none
          - bash: echo "##vso[task.setvariable variable=name;isOutput=true]name here"
            name: printvar
      - job: A2
        steps:
          - checkout: none
          - bash: echo "##vso[task.setvariable variable=name;isOutput=true]name here"

  - stage: B
    dependsOn: A
    jobs:
      - job: B1
        steps:
          - checkout: none
          - pwsh: |
              $test=@'
              $(jobsInA)
              '@
              echo $test
            env:
              jobsInA: $[ convertToJson(stageDependencies.A) ]
