strategy:
  matrix:
    linux:
      imageName: 'ubuntu-latest'
    mac:
      imageName: 'macos-latest'
    windows:
      imageName: 'windows-latest'

pool:
  vmImage: $(imageName)

steps:
- pwsh: Get-PSDrive -PSProvider FileSystem
- task: UseDotNet@2
  inputs:
    version: '9.0.100-preview.7.24406.8'
    includePreviewVersions: true
- pwsh: dotnet --info
- pwsh: dotnet workload install android ios macos tvos maccatalyst --skip-sign-check --from-rollback-file ./rollback.json --verbosity diag  --configfile ./NuGet.config
- pwsh: Get-PSDrive -PSProvider FileSystem
