pool:
  vmImage: 'windows-latest'

trigger:
  - '*'

steps:

  - task: InstallAppleCertificate@2
    inputs:
      certSecureFile: 'Testing.mobileprovision'

  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: 7.0.x

  - pwsh: |
      Invoke-WebRequest 'https://raw.githubusercontent.com/Samsung/Tizen.NET/main/workload/scripts/workload-install.ps1' -OutFile 'workload-install.ps1'
      ./workload-install.ps1 -d "$env:AGENT_TOOLSDIRECTORY/dotnet"
