pool:
  vmImage: 'ubuntu-20.04'

trigger:
  - master

steps:
 - bash: |
    sudo apt update
    sudo apt install apt-rdepends
    apt-rdepends mono-complete
    git clone --recurse-submodules https://github.com/mono/SkiaSharp.git
    cd SkiaSharp
    dotnet tool restore
    dotnet cake --target=externals-download
    dotnet cake --target=libs --skipExternals="all"