parameters:
  - name: carrots
    type: string
    default: 'yes!'

pool:
  vmImage: 'windows-latest'

variables:
  THERE_ARE_CARROTS: ${{ parameters.carrots }}

stages:
  - stage: A
    jobs:
      - job: A1
        steps:
          - checkout: none
          - pwsh: echo "$env:THERE_ARE_CARROTS"
            displayName: Good? $(THERE_ARE_CARROTS)?
