variables:
  - name: dotnet_version
    value: '9.0.100-preview.7.24406.8'

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-latest'
    mac:
      imageName: 'macos-latest'
    windows:
      imageName: 'windows-latest'

pool:
  vmImage: $(imageName)

steps:
- pwsh: |
    echo "Agent.ToolsDirectory=$(Agent.ToolsDirectory)"
    echo "Agent.TempDirectory=$(Agent.TempDirectory)"
- pwsh: Get-PSDrive -PSProvider FileSystem
- pwsh: |
    iwr 'https://raw.githubusercontent.com/dotnet/install-scripts/main/src/dotnet-install.ps1' -OutFile 'dotnet-install.ps1'
    ./dotnet-install.ps1 -InstallDir "$PWD/.dotnet" -Version '$(dotnet_version)' -Verbose
  condition: eq(variables['Agent.OS'], 'Windows_NT')
- pwsh: |
    curl -sSL https://raw.githubusercontent.com/dotnet/install-scripts/main/src/dotnet-install.sh | bash /dev/stdin --install-dir "$PWD/.dotnet" --version '$(dotnet_version)' --verbose
  condition: ne(variables['Agent.OS'], 'Windows_NT')
- pwsh: echo "##vso[task.prependpath]$PWD/.dotnet"
- pwsh: dotnet --info
- pwsh: dotnet workload install android ios maccatalyst --skip-sign-check --from-rollback-file ./rollback.json --verbosity diag  --configfile ./NuGet.config
- pwsh: Get-PSDrive -PSProvider FileSystem
