name: build

on:
  workflow_dispatch:
  push:

jobs:
  win:
    name: buildwin
    runs-on: windows-latest
    steps:
      - name: workloads
        run: dotnet workload install maui -v diag
  mac:
    name: buildmac
    runs-on: macos-latest
    steps:
      - name: workloads
        run: dotnet workload install maui -v diag
