name: build

on:
  workflow_dispatch:
  push:

jobs:
  build:
    name: build
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      - run: dotnet workload install maui
      - run: |
          dotnet workload list
          dotnet workload --info
          dotnet --info
          dotnet workload update --print-rollback

      - run: zsh build.sh
