name: build

on:
  workflow_dispatch:
  push:

jobs:
  build:
    defaults:
      run:
        shell: pwsh
    strategy:
      matrix:
        os: 
          - ubuntu-latest
          - windows-latest
          - macos-latest
    name: build
    runs-on: ${{ matrix.os }}
    steps:
      - name: get available space on agent
        run: |
          Get-PSDrive -PSProvider FileSystem
      - name: get available space on agent
        run: |
          Get-PSDrive -PSProvider FileSystem
