name: build

on:
  workflow_dispatch:
  push:

jobs:
  build:
    defaults:
      run:
        shell: pwsh
    strategy:
      matrix:
        os: 
          - ubuntu-latest
          - windows-latest
          - macos-latest
    name: build
    runs-on: ${{ matrix.os }}
    steps:
      - name: get available space on agent
        run: |
          echo "$PWD"
      - name: install .net
        if: matrix.os == 'windows-latest'
        run: |
          iwr 'https://dot.net/v1/dotnet-install.ps1' -OutFile 'dotnet-install.ps1'
          ./dotnet-install.ps1 -InstallDir "$PWD/.dotnet" -Version '9.0.0-preview.7.24405.7' -Verbose
      - name: install .net
        if: matrix.os != 'windows-latest'
        shell: bash
        run: |
          curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --install-dir "$PWD/.dotnet" ---version '9.0.0-preview.7.24405.7' --verbose
      - name: sent envvar
        run: |
          echo "$PWD/.dotnet" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      - name: check .net
        run: |
          dir env:
          dotnet --info
      - name: install .net workloads
        run: |
          dotnet workload install android ios macos tvos maccatalyst --skip-sign-check --from-rollback-file rollback.json --verbosity diag  --configfile NuGet.config
