name: build

on:
  workflow_dispatch:
  push:

jobs:
  build:
    defaults:
      run:
        shell: pwsh
    strategy:
      matrix:
        os: 
          - ubuntu-latest
          - windows-latest
          - macos-latest
    name: build
    runs-on: ${{ matrix.os }}
    steps:
      - name: get available space on agent
        run: |
          echo "$PWD"
      - name: install .net
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.100-preview.7.24406.8'
      - name: check .net
        run: |
          dotnet --info
      - name: install .net workloads
        run: |
          dotnet workload install android ios macos tvos maccatalyst --skip-sign-check --from-rollback-file rollback.json --verbosity diag  --configfile NuGet.config
